const Mobiles = [
    {
        _id: '1',
        name: "MI Redmi 7A Series Mobile Phone",
        image: '/images/electronics/mobiles/image1.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Mi-Xoumi',
        price: '$1456.99',
        countInStock: 3,
        rating: 5.0,
        numReviews: 5,
    },
    {
        _id: '2',
        name: "Samsung Galaxy Series Mobile Phone",
        image: '/images/electronics/mobiles/image2.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Samsung',
        price: '$1229.99',
        countInStock: 4,
        rating: 4.8,
        numReviews: 4,
    },
    {
        _id: '3',
        name: "Apple LX Series Mobile Phone",
        image: '/images/electronics/mobiles/image3.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Apple',
        price: '$13456.99',
        countInStock: 3,
        rating: 5.0,
        numReviews: 7,
    }
];

const Cameras = [
    {
        _id: '1',
        name: "Nikon 7A Series Camera",
        image: '/images/electronics/camera/image1.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Nikon',
        price: '$1456.99',
        countInStock: 3,
        rating: 5.0,
        numReviews: 5,
    },
    {
        _id: '2',
        name: "Flroal Series DSLR Camera",
        image: '/images/electronics/camera/image2.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Mi-Xoumi',
        price: '$12456.99',
        countInStock: 2,
        rating: 4.9,
        numReviews: 5,
    },
    {
        _id: '3',
        name: "Nikon XG Series DSLR Camera",
        image: '/images/electronics/camera/image3.jpg',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Nikon',
        price: '$13456.99',
        countInStock: 2,
        rating: 4.9,
        numReviews: 5,
    },
    {
        _id: '4',
        name: "Flroal Series Manual XL Camera",
        image: '/images/electronics/camera/image4.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Floral',
        price: '$11456.99',
        countInStock: 2,
        rating: 4.9,
        numReviews: 5,
    }
];

const Gaming = [
    {
        _id: '1',
        name: "NVIDIA GX Series Gaming Remote",
        image: '/images/electronics/gaming/image1.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'NVIDIA',
        price: '$2456.99',
        countInStock: 2,
        rating: 4.9,
        numReviews: 5,
    },
    {
        _id: '2',
        name: "AMD X Series Gaming + Mechanical Keyboard ",
        image: '/images/electronics/gaming/image2.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'AMD',
        price: '$12456.99',
        countInStock: 2,
        rating: 4.9,
        numReviews: 5,
    },
    {
        _id: '3',
        name: "AMD EGX Series Gaming Remote - Dual Set",
        image: '/images/electronics/gaming/image3.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'AMD',
        price: '$10456.99',
        countInStock: 2,
        rating: 4.8,
        numReviews: 5,
    }
];

const Sports = [
    {
        _id: '1',
        name: "MI Sports Heartbeat Tracker Wrist Watch",
        image: '/images/electronics/sports/image1.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'MI',
        price: '$2456.99',
        countInStock: 2,
        rating: 4.9,
        numReviews: 5,
    },
    {
        _id: '2',
        name: "Samsung Sports Wrist Watch",
        image: '/images/electronics/sports/image2.jpg',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'MI',
        price: '$456.99',
        countInStock: 2,
        rating: 4.9,
        numReviews: 5,
    },
    {
        _id: '3',
        name: "MI Sport Fit Bit Wrist Watch",
        image: '/images/electronics/sports/image3.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'MI',
        price: '$12456.99',
        countInStock: 2,
        rating: 4.9,
        numReviews: 5,
    },
    {
        _id: '4',
        name: "MI Sportsband + Heartbeat Tracker Wrist Watch 5 Piece Set",
        image: '/images/electronics/sports/image4.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'MI',
        price: '$32456.99',
        countInStock: 2,
        rating: 4.9,
        numReviews: 5,
    }
];

module.exports = {Mobiles, Cameras, Gaming, Sports};