const MensWear = [  
    {
        _id: '1',
        name: "Men's Fashionable Blue Coat",
        image: '/images/fashion/mens-wear/image1.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Monte Carlo',
        price: '$89.99',
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    {
        _id: '2',
        name: "Cotton White T-Shirt",
        image: '/images/fashion/mens-wear/image2.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Lenin Parker',
        price: '$49.99',
        countInStock: 7,
        rating: 4.4,
        numReviews: 7,
    },
    {
        _id: '3',
        name: "Formal White Shirt + Dark Denim",
        image: '/images/fashion/mens-wear/image3.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Monte Carlo',
        price: '$109.99',
        countInStock: 2,
        rating: 4.3,
        numReviews: 1,
    },

    {
        _id: '4',
        name: "Cream Coloured Trousers for Men",
        image: '/images/fashion/mens-wear/image4.jpg',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Terrain',
        price: '$69.99',
        countInStock: 5,
        rating: 3.5,
        numReviews: 12,
    },

    {
        _id: '5',
        name: "Light Blue Denim for Men",
        image: '/images/fashion/mens-wear/image5.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Monte Carlo',
        price: '$189.99',
        countInStock: 2,
        rating: 4.9,
        numReviews: 2,
    },

];

const WomensWear = [

    {
        _id: '1',
        name: "Fairy Flower Multicolored Dress For Girls",
        image: '/images/fashion/womens-wear/image1.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Biba',
        price: '$189.99',
        countInStock: 2,
        rating: 4.9,
        numReviews: 2,
    },
    {
        _id: '2',
        name: "White Fairy Crop Top For Girls",
        image: '/images/fashion/womens-wear/image2.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Monte Carlo',
        price: '$89.99',
        countInStock: 12,
        rating: 4.6,
        numReviews: 3,
    },
    {
        _id: '3',
        name: "Purple Flower Printed Top Wear",
        image: '/images/fashion/womens-wear/image3.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Biba',
        price: '$79.99',
        countInStock: 6,
        rating: 4.7,
        numReviews: 2,
    },
    {
        _id: '4',
        name: "Green Formal Wear Dress For Women",
        image: '/images/fashion/womens-wear/image4.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Indian Terrain',
        price: '$89.99',
        countInStock: 2,
        rating: 4.9,
        numReviews: 2,
    },
    {
        _id: '5',
        name: "Formal Black-Grey Long Coat",
        image: '/images/fashion/womens-wear/image5.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Monte Carlo',
        price: '$179.99',
        countInStock: 2,
        rating: 3.9,
        numReviews: 4,
    }
]

const OccasionalWear = [
    {
        _id: '1',
        name: "Formal Black-Grey Long Top For Women",
        image: '/images/fashion/ocassional-wear/image1.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Monte Carlo',
        price: '$79.99',
        countInStock: 2,
        rating: 3.6,
        numReviews: 4,
    },
    {
        _id: '2',
        name: "Formal Blue Tuxido Suit For Men",
        image: '/images/fashion/ocassional-wear/image2.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Manyawar',
        price: '$179.99',
        countInStock: 5,
        rating: 4.6,
        numReviews: 4,
    },
    {
        _id: '3',
        name: "Formal Black Suit Top For Men",
        image: '/images/fashion/ocassional-wear/image3.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Monte Carlo',
        price: '$279.99',
        countInStock: 2,
        rating: 4.9,
        numReviews: 4,
    },
    {
        _id: '4',
        name: "Formal Blue Long Tuxido Suit For Men",
        image: '/images/fashion/ocassional-wear/image4.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Monte Carlo',
        price: '$379.99',
        countInStock: 3,
        rating: 3.6,
        numReviews: 4,
    },
    {
        _id: '5',
        name: "Formal Flora Pink Long Suit For Women",
        image: '/images/fashion/ocassional-wear/image5.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Biba',
        price: '$79.99',
        countInStock: 5,
        rating: 4.6,
        numReviews: 5,
    }
];

const DailyWear = [
    {
        _id: '1',
        name: "Casual Shirt-Trousers For Men",
        image: '/images/fashion/daily-wear/image1.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Monte Carlo',
        price: '$179.99',
        countInStock: 2,
        rating: 4.6,
        numReviews: 4,
    },
    {
        _id: '2',
        name: "Casual White Wears For Women",
        image: '/images/fashion/daily-wear/image2.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Biba',
        price: '$279.99',
        countInStock: 7,
        rating: 4.5,
        numReviews: 3,
    },
    {
        _id: '3',
        name: "Casual Striped Print Daily Wear Top For Women",
        image: '/images/fashion/daily-wear/image3.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Indian Terrain',
        price: '$79.99',
        countInStock: 2,
        rating: 4.6,
        numReviews: 4,
    },
    {
        _id: '4',
        name: "Casual Grey Hoodie For Men",
        image: '/images/fashion/daily-wear/image4.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Monte Carlo',
        price: '$156.99',
        countInStock: 10,
        rating: 5.0,
        numReviews: 5,
    }
]


module.exports = {MensWear, WomensWear, OccasionalWear, DailyWear};