const SchoolItems = [
    {
        _id: '1',
        name: "Fun School Bag For Kids",
        image: '/images/toys/school/image1.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Fun',
        price: '$66.99',
        countInStock: 10,
        rating: 5.0,
        numReviews: 5,
    },
    {
        _id: '2',
        name: "Back To School Bag For Kids",
        image: '/images/toys/school/image2.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Back To School',
        price: '$56.99',
        countInStock: 10,
        rating: 5.0,
        numReviews: 5,
    },
    {
        _id: '3',
        name: "A + B School Kit",
        image: '/images/toys/school/image3.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'A + B',
        price: '$39.99',
        countInStock: 10,
        rating: 5.0,
        numReviews: 5,
    },
    {
        _id: '4',
        name: "Fun Slim School Bag For Kids",
        image: '/images/toys/school/image4.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Fun',
        price: '$96.99',
        countInStock: 10,
        rating: 5.0,
        numReviews: 5,
    }
];

const Teddybears = [
    {
        _id: '1',
        name: "Fun Teddy Bear For Kids",
        image: '/images/toys/teddy-bear/image1.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Fun',
        price: '$166.99',
        countInStock: 10,
        rating: 5.0,
        numReviews: 5,
    },
    {
        _id: '2',
        name: "A + B Soft Teddy Bear For Kids",
        image: '/images/toys/teddy-bear/image2.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'A + B',
        price: '$266.99',
        countInStock: 10,
        rating: 5.0,
        numReviews: 5,
    },
    {
        _id: '3',
        name: "Panda Teddy Bear For Kids",
        image: '/images/toys/teddy-bear/image3.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Panda',
        price: '$666.99',
        countInStock: 10,
        rating: 5.0,
        numReviews: 5,
    },
    {
        _id: '4',
        name: "Fun Soft Cotton Teddy Bear For Kids",
        image: '/images/toys/teddy-bear/image4.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Fun',
        price: '$766.99',
        countInStock: 10,
        rating: 5.0,
        numReviews: 5,
    }
];

const BarbieDolls = [
    {
        _id: '1',
        name: "Disney Barbie Doll For Kids",
        image: '/images/toys/barbie/image1.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Disney',
        price: '$166.99',
        countInStock: 10,
        rating: 5.0,
        numReviews: 5,
    },
    {
        _id: '2',
        name: "Disney Barbie Doll Set of Two For Kids",
        image: '/images/toys/barbie/image2.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Disney',
        price: '$299.99',
        countInStock: 10,
        rating: 5.0,
        numReviews: 5,
    },
    {
        _id: '3',
        name: "Disney Barbie Doll Set of 3 For Kids",
        image: '/images/toys/barbie/image3.webp',
        description: 'Ipsum exercitation reprehenderit dolor reprehenderit mollit in labore reprehenderit consequat qui sit proident laboris fugiat.',
        brand: 'Disney',
        price: '$466.99',
        countInStock: 10,
        rating: 5.0,
        numReviews: 5,
    }
];

module.exports = {SchoolItems, Teddybears, BarbieDolls};